### ISSUE TITLE
Deprioritize rooms with `PassedNoJoinPoint` set when matching

### ISSUE THREAD

**Issue by Beyley** [LittleBigRefresh/Refresh#373]
When the game updates the room state vita `/lbp/match`, it tells us whether the player has passed a no join gate, we should de-prioritize these rooms in the matching process, so that players are more likely to join games which they will be able to immediately play in.

**Comment by jvyden** [comment]
Pretty sure this was solved in the recent dive-in refactor.

**Comment by Beyley** [comment]
Still an issue, see [this bit of code](https://github.com/LittleBigRefresh/Refresh/blob/54ad2d5352676b22a8f70c7093c5ea394b08c894/Refresh.GameServer/Types/Matching/MatchMethods/FindRoomMethod.cs#L39), we need to save this data in our room accessor, since we currently just ignore it
